name: Deploy TERMUX-ZWD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run lint/test (optional)
      run: echo "No tests yet"

    - name: Build Docker image
      run: docker build -t termux-md .
